# 启动端口号
server:
  post: 8401

# MySQL数据源配置
mysql:
  username: root
  password: 123456
  url: tcp(localhost:3311)/imall?charset=utf8&parseTime=True&loc=Local

# Redis配置
redis:
  addr: localhost:6379
  password: 123456
  db: 0

# 图片路径配置
upload:
  savePath: /Users/zebra/sync/workspace/github/huibunny/bunnymall/demo/img
  accessUrl: http://localhost:8401/image/

# JWT配置
jwt:
  signingKey: z3d6k8v0n3w7m9sa1fd0u09h

# 定时任务
cron:
  enable: true

# 微信小程序配置
code2Session:
  appId: 	wx2c77920ca209ce27
  appSecret: 7103434068e1db5e0ebfdc48baa83b6a

# 问题反馈配置
feedback:
  qqSmtp: smtp.qq.com
  qqEmail: 1933757688@qq.com
  qqEmailSecret: jjstmwtidhwhxhzc